/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ejercicio1.h"

bool_t
xdr_INPUT_A_B (XDR *xdrs, INPUT_A_B *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  MAXIMO )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->vector, MAXIMO,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->n))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->vector;
					i < MAXIMO; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->n);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  MAXIMO )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->vector, MAXIMO,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->n))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->vector;
					i < MAXIMO; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->n = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->vector, MAXIMO,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OUTPUT_A (XDR *xdrs, OUTPUT_A *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->media))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OUTPUT_B (XDR *xdrs, OUTPUT_B *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->maximo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_INPUT_OUTPUT_C (XDR *xdrs, INPUT_OUTPUT_C *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->factorial))
		 return FALSE;
	return TRUE;
}
