/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJERCICIO1_H_RPCGEN
#define _EJERCICIO1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXIMO 10

struct INPUT_A_B {
	int vector[MAXIMO];
	int n;
};
typedef struct INPUT_A_B INPUT_A_B;

struct OUTPUT_A {
	float media;
};
typedef struct OUTPUT_A OUTPUT_A;

struct OUTPUT_B {
	int maximo;
};
typedef struct OUTPUT_B OUTPUT_B;

struct INPUT_OUTPUT_C {
	int factorial;
};
typedef struct INPUT_OUTPUT_C INPUT_OUTPUT_C;

#define CALCULADORA 0xAB000003
#define CALCULADORA_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define a 1
extern  OUTPUT_A * a_1(INPUT_A_B *, CLIENT *);
extern  OUTPUT_A * a_1_svc(INPUT_A_B *, struct svc_req *);
#define b 2
extern  OUTPUT_B * b_1(INPUT_A_B *, CLIENT *);
extern  OUTPUT_B * b_1_svc(INPUT_A_B *, struct svc_req *);
#define c 3
extern  INPUT_OUTPUT_C * c_1(INPUT_OUTPUT_C *, CLIENT *);
extern  INPUT_OUTPUT_C * c_1_svc(INPUT_OUTPUT_C *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define a 1
extern  OUTPUT_A * a_1();
extern  OUTPUT_A * a_1_svc();
#define b 2
extern  OUTPUT_B * b_1();
extern  OUTPUT_B * b_1_svc();
#define c 3
extern  INPUT_OUTPUT_C * c_1();
extern  INPUT_OUTPUT_C * c_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_INPUT_A_B (XDR *, INPUT_A_B*);
extern  bool_t xdr_OUTPUT_A (XDR *, OUTPUT_A*);
extern  bool_t xdr_OUTPUT_B (XDR *, OUTPUT_B*);
extern  bool_t xdr_INPUT_OUTPUT_C (XDR *, INPUT_OUTPUT_C*);

#else /* K&R C */
extern bool_t xdr_INPUT_A_B ();
extern bool_t xdr_OUTPUT_A ();
extern bool_t xdr_OUTPUT_B ();
extern bool_t xdr_INPUT_OUTPUT_C ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJERCICIO1_H_RPCGEN */
