/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ejercicio1.h"


void
calculadora_1(char *host, int *v, int n)
{
	CLIENT *clnt;
	OUTPUT_A  *result_1;
	INPUT_A_B  a_1_arg;
	OUTPUT_B  *result_2;
	INPUT_A_B  b_1_arg;
	INPUT_OUTPUT_C  *result_3;
	INPUT_OUTPUT_C  c_1_arg;
	int opcion=0;

	for(int x=0; x<n; x++){
		a_1_arg.vector[x]=v[x];
		b_1_arg.vector[x]=v[x];
	}
	a_1_arg.n=n;
	b_1_arg.n=n;
#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

		printf("1.Calcular la media aritmetica\n");
		printf("2.Calcular el maximo de un vector\n");
		printf("3.Calcular el factorial de un numero\n");
		printf("Seleccione una de las opciones\n");
		scanf("%i", &opcion);

		switch(opcion){
			case 1:
				//a_1_arg.vector=v;
				//	
				result_1 = a_1(&a_1_arg, clnt);
				if (result_1 == (OUTPUT_A *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("La media aritmetica es %f\n", result_1->media);
				}
				break;

			case 2:
				//b_1_arg.vector=v;
				//b_1_arg.n=n;	
				result_2 = b_1(&b_1_arg, clnt);
				if (result_2 == (OUTPUT_B *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("El numero más grande del vector es %i\n", result_2->maximo);
				}
				break;

			case 3:
				printf("Introduzca un numero para calcular su factorial\n");	
				scanf("%i", &(c_1_arg.factorial));
				result_3 = c_1(&c_1_arg, clnt);
				if (result_3 == (INPUT_OUTPUT_C *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("El factorial de %i es %i\n", c_1_arg.factorial, result_3->factorial);
				}
				break;
			
			default:
				printf("error de selecion\n");
				break;
		}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int v[10];
	int j=0;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	for(int i=2; i<argc; i++){
		v[j]=atoi(argv[i]);
		j++;			
	}
	calculadora_1 (host, v, j);
exit (0);
}
