/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ejercicio2.h"


void
bases_datos_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	INPUT_A  a_1_arg;
	void  *result_2;
	INPUT_B  b_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BASES_DATOS, BASES_DATOS_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = a_1(&a_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = b_1(&b_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bases_datos_1 (host);
exit (0);
}
