/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "ejercicio2.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

OUTPUT_A_B *
a_1(INPUT_A *argp, CLIENT *clnt)
{
	static OUTPUT_A_B clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, A,
		(xdrproc_t) xdr_INPUT_A, (caddr_t) argp,
		(xdrproc_t) xdr_OUTPUT_A_B, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

OUTPUT_A_B *
b_1(INPUT_B *argp, CLIENT *clnt)
{
	static OUTPUT_A_B clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, B,
		(xdrproc_t) xdr_INPUT_B, (caddr_t) argp,
		(xdrproc_t) xdr_OUTPUT_A_B, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
